# Generated by Django 2.2.27 on 2022-03-22 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.CharField(default='A course for GAs', max_length=128),
        ),
        migrations.AddField(
            model_name='course',
            name='start',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='Unnamed', max_length=128),
        ),
    ]
